package ModandControl;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import com.fasterxml.jackson.databind.util.JSONPObject;
import jdk.nashorn.internal.parser.JSONParser;
import org.hibernate.exception.DataException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/painter") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@Autowired
	private HttpServletRequest request;

	@Autowired
	private BoardRepository boardRepository;


	    //TODO: Allow the same user to open few pages, first add checking if the user is inside the database.
	    @GetMapping("/createBoard")
	    public @ResponseBody String createBoard(){
	        Board board1=new Board();
            board1.setMaxShapes(Constants.DEFAULTMAXSHAPES);
            User admin=new User();
            admin.setIp(request.getRemoteHost());
            board1.setAdmin(admin);
	        board1.startBoard();
            userRepository.save(admin);
	        boardRepository.save(board1);
	        return "ModandControl/Board" +board1.getId()+ " has been created, toggle to /board to add shapes";
        }

        @DeleteMapping("/board/deleteShape")
        public @ResponseBody  String deleteShape(@RequestBody String stringifiedObj) {
            JsonNode jsonObject = convertToJSONObj(stringifiedObj);
            if (jsonObject != null) {
                String ip=request.getRemoteHost();
                User user=userRepository.findUserByIp(ip);
                Shape shapetoRemove = createProperShape(jsonObject,true);
                Optional<Board> getBoard = boardRepository.findById(1);
                if (getBoard.isPresent()) {
                    Board myboard = getBoard.get();
                    if (user!=null && user.getIp().equals(myboard.getAdmin().getIp()) && myboard.removeShape(shapetoRemove, user)) {
                        boardRepository.save(myboard);
                    }
                }
            }
            return "";
        }


        @PostMapping("/board/boardAddShapeTest")
        public @ResponseBody  String test(@RequestBody String str) {
            JsonNode jsonObject = convertToJSONObj(str);
            if (jsonObject != null) {
                String ip=request.getRemoteHost();
                User user=userRepository.findUserByIp(ip);
                Shape shapetoAdd = createProperShape(jsonObject,false);
                Optional<Board> getBoard = boardRepository.findById(1);
                if (getBoard.isPresent()) {
                    Board myboard = getBoard.get();
                    if (user!=null && myboard.addShape(shapetoAdd,user)) {
                        boardRepository.save(myboard);
                    }

                }
            }
            return "";
        }



        @GetMapping("/board/getShapes")
        public @ResponseBody String getCurrentShapes(){
	        Optional<Board> getboard=boardRepository.findById(1);
	        if(getboard.isPresent()){
	            getboard.get().resetAccordingTheDay();
	            return getboard.get().stringfyShapes();
            }
	        else
                return "";
        }

        @GetMapping("/board")
        public @ResponseBody ModelAndView showBoard(){
	        Optional<Board> getboard=boardRepository.findById(1);
	        String ip=request.getRemoteHost();
	        User user=userRepository.findUserByIp(ip);
            ModelAndView mdl=new ModelAndView("board");
	        if(getboard.isPresent()){
                Board myboard=getboard.get();
                if(user==null){
                    User newUser=new User();
                    newUser.setIp(ip);
                    myboard.addUser(newUser);
                    userRepository.save(newUser);
                }else if(!myboard.containsUser(user)){
                    myboard.addUser(user);
                }
                    getboard.get().resetAccordingTheDay();
                    boardRepository.save(myboard);
	                mdl.addObject("board",myboard);
	                return mdl;
            }
	        else
                return mdl;
        }



		@GetMapping(path = "/add") // Map ONLY GET Requests
		public @ResponseBody String addNewUser (@RequestParam String name){
			// @ResponseBody means the returned String is the response, not a view name
			// @RequestParam means it is a parameter from the GET or POST request

			User n = new User();
			n.setIp(request.getRemoteHost());
			System.out.println(request.getRemoteHost());
			userRepository.save(n);
			return (name + " Saved " + request.getRemoteHost());
		}

		@GetMapping(path = "/all")
		public @ResponseBody Iterable<User> getAllUsers () {
			// This returns a JSON or XML with the users
			return userRepository.findAll();
		}

		private JsonNode convertToJSONObj(String toConvert){
            ObjectMapper mapper = new ObjectMapper();
            JsonNode jsonObject = null;
            try {
                jsonObject = mapper.readTree(toConvert);
            } catch (IOException e) {
                System.out.println("Couldn't parse str");
            }
            return jsonObject;
        }
        private Shape createProperShape(JsonNode jsonObject,Boolean toDeletion){
            Shape shapetoAdd = null;
            String name = jsonObject.get("name").asText();
            if (name.equals("Triangle")) {
                shapetoAdd = new Triangle();
                ((Triangle) shapetoAdd).setSize(jsonObject.get("size").asInt());
            } else if (name.equals("Square")) {
                shapetoAdd = new Square();
                ((Square) shapetoAdd).setSize(jsonObject.get("size").asInt());
            } else if (name.equals("Circle")) {
                shapetoAdd = new Circle();
                ((Circle) shapetoAdd).setRadius(jsonObject.get("radius").asInt());
            }
            if(shapetoAdd!=null) {
                shapetoAdd.setX(jsonObject.get("x").asInt());
                shapetoAdd.setY(jsonObject.get("y").asInt());
            }
            if(toDeletion)
                shapetoAdd.setId(jsonObject.get("id").asInt());
            return shapetoAdd;
        }
	}

	//<svg width="80" height="80">
//    <circle cx="40" cy="40" r="30" stroke="#000" stroke-width="1" fill="#FFF" />
//</svg>
